root: true

env:
  browser: true
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended

plugins:
  - import

parserOptions:
  parser: '@typescript-eslint/parser'
  project:
    - './tsconfig.json'

ignorePatterns:
  - '**/dist/**'
  - '**/node_modules/**'
  - '**/library/**'
  - '**/public/**'
  - '**/scripts/**'
  - '**/.vitepress/cache/'

rules:
  '@typescript-eslint/no-floating-promises': off
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/consistent-type-imports': off
  '@typescript-eslint/explicit-function-return-type': off

  '@typescript-eslint/naming-convention':
    - off
    - selector: default
      format:
        - camelCase
      leadingUnderscore: allowSingleOrDouble
      trailingUnderscore: allow

    - selector:
        - variable
      format:
        - camelCase
        - PascalCase
        - UPPER_CASE
      leadingUnderscore: allowSingleOrDouble
      trailingUnderscore: allowSingleOrDouble

    - selector:
        - parameter
      format:
        - camelCase
        - PascalCase
      leadingUnderscore: allow
      trailingUnderscore: allow

    - selector:
        - property
      format: null
      # allow locales path like `/zh/`, alias starting with `@` and css property like `line-width`
      filter: (^/$|^/.*/$|^@|^[a-z]+(?:-[a-z]+)*?$)
      leadingUnderscore: allow
      trailingUnderscore: allow

    - selector:
        - property
      format:
        - camelCase
        - PascalCase
        - UPPER_CASE
      leadingUnderscore: allow
      trailingUnderscore: allow

    - selector: import
      format:
        - PascalCase
        - camelCase

    - selector: typeLike
      format:
        - PascalCase

  '@typescript-eslint/no-explicit-any':
    - warn
    - ignoreRestArgs: true

  '@typescript-eslint/no-non-null-assertion':
    - off

  '@typescript-eslint/no-unsafe-assignment':
    - warn

  '@typescript-eslint/no-unsafe-enum-comparison':
    - off

  '@typescript-eslint/no-unsafe-member-access':
    - warn

  '@typescript-eslint/no-unsafe-return':
    - warn

  curly:
    - error
    - all

  import/consistent-type-specifier-style:
    - error
    - prefer-top-level

  import/first:
    - error

  import/newline-after-import:
    - error

  import/no-commonjs:
    - off

  import/no-cycle:
    - error

  import/no-duplicates:
    - error
    - considerQueryString: true

  import/no-named-default:
    - error

  import/order:
    - error
    - alphabetize:
        order: asc
        orderImportKind: asc
      groups:
        - builtin
        - external
        - internal
        - - parent
          - sibling
        - index
        - object
      newlines-between: always

  no-duplicate-imports:
    - off

  no-unmodified-loop-condition:
    - error

  padding-line-between-statements:
    - error
    - blankLine: always
      prev:
        - const
        - let
      next:
        - '*'
    - blankLine: any
      prev:
        - const
        - let
      next:
        - const
        - let
    - blankLine: always
      prev:
        - '*'
      next:
        - return

  sort-imports:
    - error
    - allowSeparatedGroups: false
      ignoreDeclarationSort: true
